<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr=np.insert(arr,2,[3,4])
print(arr)




[10 20  3  4 30 40 50 60]


In [9]:
import numpy as np
arr  = np.array([[2,3,4],[4,5,6]])
arr = np.insert(arr,2,[4,5,9],axis=0)
print(arr)
print(np.delete(arr,2,axis=0))
print(arr)

[[2 3 4]
 [4 5 6]
 [4 5 9]]
[[2 3 4]
 [4 5 6]]
[[2 3 4]
 [4 5 6]
 [4 5 9]]


In [10]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr=np.delete(arr,(3,4))
print(arr)

[10 20 30 60]


In [14]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))

[19 22]
[ 4 12  8 10  7]


In [15]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.max(arr))

9


In [16]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.min(arr))

2


In [17]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.var(arr))

4.090000000000001


In [18]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.mean(arr))

4.1


In [19]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.std(arr))

2.022374841615669


In [29]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.percentile(arr,[30,80 ,45,100]))

[2.7 5.  4.  9. ]


In [28]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.quantile(arr,1))

9


In [35]:
import numpy as np
arr = np.array([[2,3,4,5,5],[3,2,9,4,5]])
print(np.argmax(arr))

7


In [36]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.argmin(arr))

0


In [41]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.log10(arr))
print(np.log2(arr))

[[0.30103    0.47712125 0.60205999 0.69897    0.69897   ]
 [0.30103    0.95424251 0.60205999 0.69897    0.30103   ]]
[[1.         1.5849625  2.         2.32192809 2.32192809]
 [1.         3.169925   2.         2.32192809 1.        ]]


In [42]:
import numpy as np
arr = np.array([[2,3,4,5,5],[2,9,4,5,2]])
print(np.sqrt(arr))

[[1.41421356 1.73205081 2.         2.23606798 2.23606798]
 [1.41421356 3.         2.         2.23606798 1.41421356]]


In [46]:
import numpy as np
arr = np.array([2.3,3.56,4.89,5.90,5.78])
print(np.round(arr))
print(np.round(arr,2))

[2. 4. 5. 6. 6.]
[2.3  3.56 4.89 5.9  5.78]


In [47]:
import numpy as np
arr = np.array([2.3,3.56,4.89,5.90,5.78])
print(np.floor(arr))

[2. 3. 4. 5. 5.]


In [49]:
import numpy as np
arr = np.array([2.3,3.56,4.89,5.90,5.78])
print(np.ceil(arr))

[3. 4. 5. 6. 6.]


In [54]:
import numpy as np
arr = np.array([-2.3,3.56,4.89,-5.90,5.78])
print(np.abs(arr))

[5.78 5.9  4.89 3.56 2.3 ]


In [56]:
import numpy as np
arr = np.array([-2.3,3.56,4.89,-5.90,5.78])
print(np.sort(arr))

[-5.9  -2.3   3.56  4.89  5.78]
