<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#np.linspace(start,end,size)
import numpy as np
uu = np.linspace(1,100,4)
print(uu)

[  1.  34.  67. 100.]


In [9]:
#ravel() it 2d array into 1d array
import numpy as np
ii = np.arange(1,100).reshape((1,9,11))
print(ii)
print(ii.ravel())

[[[ 1  2  3  4  5  6  7  8  9 10 11]
  [12 13 14 15 16 17 18 19 20 21 22]
  [23 24 25 26 27 28 29 30 31 32 33]
  [34 35 36 37 38 39 40 41 42 43 44]
  [45 46 47 48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63 64 65 66]
  [67 68 69 70 71 72 73 74 75 76 77]
  [78 79 80 81 82 83 84 85 86 87 88]
  [89 90 91 92 93 94 95 96 97 98 99]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [10]:
#(.T) transpose matrixs
import numpy as np
arr = np.arange(1,19).reshape(6,3)
print(arr)
arr.T

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [11]:
#(.size) to know no.of elememts in array
import numpy as np
arr = np.arange(1,19)
print(arr)
arr.size

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


18

In [25]:
import numpy as np
arr = np.arange(1,19)
print(arr)
arr[5:]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [34]:
import numpy as np
arr = np.array([[10,20,30,384,2344,234]])
print(arr.shape)
arr[0,5]=8384
print(arr)

(1, 6)
[[  10   20   30  384 2344 8384]]


In [40]:
#np.insert()
import numpy as np
arr =np.array([10,20,30,40,50])
ll=np.insert(arr,4,[100,56879809,44576,6899])
print(ll)

[      10       20       30       40      100 56879809    44576     6899
       50]


In [42]:
#np.delete()
import numpy as np
arr =np.array([10,20,30,40,50])
arr = np.delete(arr,[1,2])
print(arr)

[10 40 50]
