<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = [23,223,5,3,12,45,62]
n = np.array(a)
print(n)

print(np.__version__)
print(n.ndim)

n.shape



[ 23 223   5   3  12  45  62]
2.1.3
1


(7,)

In [ ]:
import numpy as np
arr = np.array([[3,4,5],[2,4,5]])
print(arr)
print(arr.ndim)
arr.shape


[[3 4 5]
 [2 4 5]]
2


(2, 3)

In [ ]:
import numpy as np
arr = np.array([[[3,4,5],[2,'huuiu',5]],[[2,4,9],[34,'45',9]]])
print(arr)
print(arr.ndim)
print(arr.dtype)
arr.shape


[[['3' '4' '5']
  ['2' 'huuiu' '5']]

 [['2' '4' '9']
  ['34' '45' '9']]]
3
<U21


(2, 2, 3)

In [7]:
import numpy as np
arr=np.zeros((2,9,9))
#arr=np.zeros(10)
print(arr)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [8]:
import numpy as np
#arr=np.ones(100)
arr = np.ones((3,23,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
import numpy as np
#arr=np.full(10,23)
#arr =np.full((2,3),23)
arr = np.full((3,2,3),253)
print(arr)

[[23 23 23]
 [23 23 23]]


In [12]:
#np.arange()
import numpy as np
arr=np.arange(3,34,6)
print(arr)

[ 3  9 15 21 27 33]


In [21]:
#reshape()
import numpy as np
arr = np.arange(1,9)
print(arr)
print(arr.reshape(4,2))

#reshape 2d array
hh =np.array([[2,3,4,2,5],[23,88,23,3,2]])
print(hh.reshape(10,))



[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 2  3]
 [ 4  2]
 [ 5 23]
 [88 23]
 [ 3  2]]


In [27]:
#indentiy matrixs  = np.eye()
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
#random.random()= gentrate random number between 0 and 1 only float values
rr =np.random.random(4)
hh =np.random.random((2,3) )
jj=np.random.random((4,2,3) )
print(rr)
print(hh)
print(jj.ndim)

[0.41072572 0.22993386 0.83850883 0.58643077]
[[0.01033557 0.75649747 0.24954639]
 [0.8338972  0.75093025 0.90443169]]
3


In [59]:
#np.random.unifrom(low,high,size)
import numpy as np
arr = np.random.uniform(-23,23,100)
print(arr.reshape(4,25))



[[-19.32885317 -14.35225416  -3.63532212  14.78943833 -19.34126726
  -10.76666684 -19.95165848   3.83381087  12.93921218  -4.73503334
   -0.53724483   3.24749695 -11.84313122  19.50122062 -17.54022556
   10.65031626  13.63703395  10.78849286 -12.82939174   7.3400738
   11.47809231 -20.63847554  -5.83182806 -10.98800225 -19.98733182]
 [-16.80974058  15.33104668 -21.28741396   8.78417122 -11.76052555
   -5.9128652   -4.85192762  -8.26859383  12.44056443   5.2786648
    9.61216907 -17.8269593  -13.61363577  -0.79354458 -11.31718762
  -11.22650923   7.20385348  10.51170701 -22.22653173  -5.54151896
  -15.8405982    6.01547701   9.8819954   -6.09851029  13.28091177]
 [  0.65307046 -15.58798401 -20.34174764 -22.54805864   9.27908963
   -8.05847422 -22.60434352   1.96711499   9.76231742   3.31135644
  -21.32438421 -19.16532592  11.65623751   6.26805143  21.80071655
   14.83904943  16.07383553 -12.78971526  16.34849824  -5.63294615
    3.0030426  -14.60795801  18.9784385  -22.37739838  22.9824

In [68]:
#np.random.randn() .mean of elements is 0 and stdevtion is 1
arr = np.random.randn(5)
hh=np.random.randn(2,3)
print(arr)
print(hh)

[-0.00947034  1.16685142  0.4750401  -1.69782303 -1.63350151]
[[ 0.09957516 -0.33632649 -0.06879805]
 [-0.64246734 -1.04653181  0.26325748]]


In [101]:
#np.random.choice()
arr = np.array([23,45,21,16,17,19])
result = np.random.choice(arr,3)
print(result)

hh = np.array(['ravi','sun','moon','dog'])
re = np.random.choice(hh,2)
print(re)
#choice with probility
uu = np.array([23,32,4])
ff = np.random.choice(uu,size=1,p=[0.3,0.2,0.5])
print(ff)

[19 45 19]
['moon' 'dog']
[32]


In [121]:
#np.random.seed()
arr = np.random.random(23)
np.random.seed()
print(arr)


[0.0286853  0.90441142 0.8141145  0.41891428 0.10529514 0.89461952
 0.28725088 0.25218211 0.88419305 0.70749599 0.08399674 0.02633224
 0.11842069 0.18481737 0.44693146 0.37801181 0.26246972 0.56896958
 0.2760729  0.79811932 0.0605603  0.63641985 0.89734151]


In [136]:
#np.random.randint()
import numpy as np
num = np.random.randint(3,99,4)
print(num)

[34 38 92 38]


In [148]:
#np.random.shuffle()
aa = np.array([23,12,32,123,3242,21,1234])
np.random.shuffle(aa)
print(aa)


[  12  123   21   23 3242 1234   32]


In [145]:
#np.random.permutation()
aa = np.array([23,12,32,123,3242,21,1234])
np.random.permutation(aa)
print(aa)


[  23   12   32  123 3242   21 1234]
