<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/numpy_questions_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64


In [4]:
import numpy as np
arr =np.arange(1,13).reshape(3,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
import numpy as np
arr = np.zeros(4)
print(arr)
ar=np.zeros((2,3))
print(ar)
a=np.zeros((3,4,3))
print(a)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
import numpy as np
ar=np.ones((2,3))
print(ar)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import numpy as np
arr =np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [11]:
import numpy as np
ar=np.eye(4)
print(ar)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
import numpy as np
arr = np.random.random(5)
print(arr)

[0.38306433 0.93380533 0.42776328 0.77087091 0.69774145]


In [13]:
import numpy as np
arr = np.random.random((2,3))
print(arr)

[[0.43417993 0.39064516 0.14609584]
 [0.69706522 0.98807155 0.40575637]]


In [15]:
import numpy as np
arr = np.random.uniform(10,50,9).reshape(3,3)
print(arr)

[[19.11444949 42.24175775 39.41807231]
 [41.1332726  10.97262556 28.05888849]
 [23.1572252  45.87110543 24.67924164]]


In [19]:
import numpy as np
arr = np.random.randn(2,4)
print((arr))

[[-0.96061129 -1.25916182  0.20431381 -0.41770666]
 [ 0.09696225 -0.21916681  0.14461671 -0.13729837]]


In [22]:
import numpy as np
arr = ["red","bule","green","Yellow","Black"]
jj=np.array(arr)
print(np.random.choice(jj,3))


['red' 'bule' 'Yellow']


In [71]:
import numpy as np
arr = np.random.randint(10,30,5)
np.random.seed(23)
print((arr))

[29 16 18 19 18]


In [96]:
import numpy as np
arr = np.arange(5,50,5)
aa=np.linspace(5,50,5)
print(arr)
print(aa)

[ 5 10 15 20 25 30 35 40 45]
[ 5.   16.25 27.5  38.75 50.  ]


In [79]:
import numpy as np
arr =np.arange(1,10)
aa=np.random.permutation(arr)
print(arr)
print(aa)

[1 2 3 4 5 6 7 8 9]
[7 2 9 3 5 6 8 1 4]


In [100]:
import numpy as np
arr =np.arange(1,10)
np.random.shuffle(arr)
print(arr)

[4 5 3 7 6 9 1 8 2]


In [97]:
import numpy as np
aa=np.linspace(0,100,6)
print(aa)

[  0.  20.  40.  60.  80. 100.]


In [103]:
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)
print(np.ravel(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [111]:
import numpy as np
arr = np.arange(1,7).reshape(2,3)
print(arr.T)
print(arr.reshape(3,1,2))

[[1 4]
 [2 5]
 [3 6]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [158]:
import numpy as np
arr = np.arange(10,60,10)
print(arr.dtype)
arr=arr.astype("float")
print(arr.dtype)

int64
float64


In [159]:
import numpy as np
arr =np.arange(10,100,10).reshape(3,3)
print(arr)
print(arr[1,1])
print(arr[2])
print(arr[:3,:2])
arr[2,1] = 800
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[70 80 90]
[[10 20]
 [40 50]
 [70 80]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70 800  90]]


In [155]:
import numpy as np
arr = np.arange(10,60,10)
np.insert(arr,2,[25])
np.delete(arr,4)
np.sum(arr)
np.min(arr)
np.max(arr)
np.mean(arr)

np.float64(30.0)

In [165]:
import numpy as np
arr = np.array([45,56,67,72,81,90,95])
np.var(arr)
np.std(arr)
np.percentile(arr,25)
np.percentile(arr,75)
np.argmax(arr)
np.argmin(arr)
print(np.log10(arr))

[1.65321251 1.74818803 1.8260748  1.8573325  1.90848502 1.95424251
 1.97772361]


In [179]:
import numpy as np
a =np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9])
print(np.concatenate((a,b)))
print(np.stack((a,b)))
print(np.stack((a,b,c),axis=1))
print(np.split(a,3,axis=0))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[array([1]), array([2]), array([3])]
