<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/questions_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
dd = np.arange(10,50,5)
print(dd)

[10 15 20 25 30 35 40 45]


In [ ]:
iimport numpy as np
dd = np.arange(10,50,5)
print(dd)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
import numpy as np
dd = np.arange(1001,1021)
print(dd)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]


In [ ]:
import numpy as np
dd = np.arange(50,0,-1)
print(dd)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [ ]:
import numpy as np
rol = np.array([101,102,103,104,105,106,107,108])
np.random.shuffle(rol)
print(rol)

[103 102 105 101 107 108 104 106]


In [ ]:
import numpy as np
rol = np.array(['ravi','priya','arun','sneha','kiran'])
np.random.shuffle(rol)
print(rol)

['ravi' 'kiran' 'arun' 'sneha' 'priya']


In [ ]:
import numpy as np
rol = np.array([10,20,30,40,50])
print(np.random.permutation(rol))
print(rol)

[20 10 30 50 40]
[10 20 30 40 50]


In [ ]:
import numpy as np
mark = np.arange(24,48)
print(mark.reshape(4,6))

[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [ ]:
import numpy as np
mark = np.arange(1,21)
print(mark.reshape(4,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
ee= np.zeros(5)
print(ee.shape)
ff= np.zeros((3,4))
print(ff.shape)
gg= np.zeros((2,3,4))
print(gg.shape)

(5,)
(3, 4)
(2, 3, 4)


In [ ]:
import numpy as np
ee= np.ones(5)
print(ee.ndim)
hh=np.ones((2,3))
print(hh.ndim)
jj=np.ones((2,2,3))
print(jj.ndim)


1
2
3


In [ ]:
import numpy as np
hh =np.full((4,5),1000)
print(hh)

[[1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]]


In [ ]:
import numpy as np
uu = np.eye(5)
print(uu)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
pp =np.arange(101,120)
print(pp)
np.random.shuffle(pp)
print(pp)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119]
[118 108 104 109 110 101 111 107 102 117 105 106 112 113 103 114 115 116
 119]


In [ ]:
import numpy as np
pp =np.arange(1,10)
print(pp)
ll=np.random.permutation(pp)
print(ll)

[1 2 3 4 5 6 7 8 9]
[6 8 4 3 5 7 1 9 2]


In [ ]:
import numpy as np
ii =np.arange(1,25)
print(ii.shape)
print(ii.reshape(4,6))
print(ii.shape)


(24,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(24,)


In [ ]:
import numpy as np
ii =np.random.random((3,4))
kk=np.random.random((2,3,4))
print(ii)
print(kk)

[[0.42750709 0.24471941 0.42202358 0.09125532]
 [0.17716498 0.88428709 0.09505704 0.87207511]
 [0.10343531 0.8517666  0.20261972 0.55196182]]
[[[0.23550862 0.46954623 0.15264133 0.50221215]
  [0.90616292 0.60140013 0.75394353 0.03387422]
  [0.91714479 0.71102903 0.73502764 0.45214782]]

 [[0.59067157 0.12734783 0.6606791  0.27192178]
  [0.7075978  0.40465735 0.91384775 0.72414213]
  [0.06370974 0.91966968 0.53630302 0.23114054]]]


In [ ]:
import numpy as np
ii =np.random.uniform(50,100,10)
kk=np.random.uniform(10,20,9).reshape(3,3)
print(ii)
print(kk)

[55.65133398 76.19113411 82.07842467 60.61937868 61.3136579  98.6635793
 57.71049225 99.22377524 76.22591644 90.10836949]
[[17.64136913 17.87163517 17.54063056]
 [14.27939695 16.83503796 14.18235144]
 [17.98757809 15.94887432 13.27695317]]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [ ]:
import numpy as np
rr = np.array([45,78,92,56,88,67,34])
print(np.max(rr))
print(np.min(rr))


92
34


In [ ]:
import numpy as np
arr = np.array([12000,15000,18000,11000,20000])
print(np.mean(arr))

15200.0


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.var(arr))

200.0


In [ ]:
import numpy as np
arr = np.array([60,70,80,90,100])
print(np.std(arr))

14.142135623730951


In [ ]:
import numpy as np
arr = np.array([35,42,55,60,68,72,80,85,95,100])
print(np.percentile(arr,50))

70.0


In [ ]:
import numpy as np
arr = np.array([25000,30000,35000,40000,45000])
print(np.quantile(arr,[0.25,0.75]))

[30000. 40000.]


In [ ]:
import numpy as np
arr = np.array([15000,22000,18000,35000,27000,12000])
print(np.argmax(arr))

3


In [ ]:
import numpy as np
arr = np.array([32,28,35,25,30,22,38])
print(np.argmin(arr))

5


In [ ]:
import numpy as np
arr = np.array([10,100,1000,10000])
print(np.log10(arr))

[1. 2. 3. 4.]


In [ ]:
import numpy as np
arr = np.array([1,2,4,8,16,32])
print(np.log2(arr))

[0. 1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
arr = np.array([4,9,16,25,36,49])
print(np.sqrt(arr))

[2. 3. 4. 5. 6. 7.]


In [ ]:
import numpy as np
arr = np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(arr))

[12. 24. 46. 56. 79.]


In [ ]:
import numpy as np

arr = np.array([10.2,15.8,20.4,25.9,301])
print(np.floor(arr))

[ 10.  15.  20.  25. 301.]


(None,)